package com.jakipradip.myEnum;

public enum Destination {
	DALLAS, ARLINGTON, AUSTIN, NEWORLEANS, ADDISON, MCKINNEY, PLANO, GRAPEVINE, SANANTINO, COMMERCE, FORTWORTH, COPPELL, FARMERSRANCH, WILEY, IRVING, HOUSTON;
}
