package com.jakipradip.dao;

public interface QueryConstant {
	String FIND_ROUTE_ALL = "FIND_ROUTE_ALL";
	String FIND_ROUTE_BY_ID = "FIND_ROUTE_BY_ID";
	String FIND_ROUTE_BY_ACTIVESTATUS = "FIND_ROUTE_BY_ACTIVESTATUS";
	String FIND_ROUTE_BY_ANYFIELD = "FIND_ROUTE_BY_ANYFIELD";
	String FIND_ROUTE_BY_E_DEST = "FIND_ROUTE_BY_E_DEST";
	String FIND_ROUTE_BY_S_DEST = "FIND_ROUTE_BY_S_DEST";
	String FIND_ROUTE_BY_NAME = "FIND_ROUTE_BY_NAME";
	String COUNT_ROUTE_BY_NAME = "COUNT_ROUTE_BY_NAME";

	String FIND_VEHICLE_ALL = "FIND_VEHICLE_ALL";
	String FIND_VEHICLE_BY_ACTIVESTATUS = "FIND_VEHICLE_BY_ACTIVESTATUS";
	String FIND_VEHICLE_BY_ANYFIELD = "FIND_VEHICLE_BY_ANYFIELD";
	String FIND_VEHICLE_BY_DUTYSTATUS = "FIND_VEHICLE_BY_DUTYSTATUS";
	String FIND_VEHICLE_BY_ID = "FIND_VEHICLE_BY_ID";
	String FIND_VEHICLE_BY_NAME = "FIND_VEHICLE_BY_NAME";
	String FIND_VEHICLE_BY_REGNUM = "FIND_VEHICLE_BY_REGNUM";
	String FIND_VEHICLE_BY_TYPE = "FIND_VEHICLE_BY_TYPE";
	String COUNT_VEHICLE_BY_REGNUM = "COUNT_VEHICLE_BY_REGNUM";

	String FIND_SCHEDULE_ALL = "FIND_SCHEDULE_ALL";
	String FIND_SCHEDULE_BY_ID = "FIND_SCHEDULE_BY_ID";
	String GENERATE_SCHEDULE_ID = "GENERATE_SCHEDULE_ID";

}
